 function changeselect1(locationid) 
{ 
	 var subcat=new Array(); 
	 var biglist=new Array('电脑网络','休闲娱乐','商业经济','生活服务','教育文化');
	   
	 subcat[0]=new Array('1','音乐mp3','音乐mp3') 
	 subcat[1]=new Array('1','聊天QQ','聊天QQ') 
	 subcat[3]=new Array('1','爱情交友','爱情交友') 
	 subcat[4]=new Array('1','明星美女','明星美女') 
	 subcat[5]=new Array('1','娱乐八卦','娱乐八卦') 
	 subcat[6]=new Array('1','星相命理','星相命理') 
	 subcat[7]=new Array('1','游戏网游','游戏网游') 
	 subcat[8]=new Array('4','军事国防','军事国防') 
	 subcat[9]=new Array('4','体育运动','体育运动') 
	 subcat[10]=new Array('4','足球世界','足球世界') 
	 subcat[11]=new Array('4','篮球运动','篮球运动') 
	 subcat[12]=new Array('3','彩票博彩','彩票博彩') 
	 subcat[13]=new Array('3','宠物花鸟','宠物花鸟') 
	 subcat[14]=new Array('1','动漫卡通','动漫卡通') 
	 subcat[15]=new Array('1','壁纸图片','壁纸图片') 
	 subcat[17]=new Array('1','影视宽带','影视宽带') 
	 subcat[18]=new Array('3','手机通信','手机通信') 
	 subcat[19]=new Array('0','WAP网站','WAP网站') 
	 subcat[20]=new Array('3','家电数码','家电数码') 
	 subcat[21]=new Array('2','新闻媒体','新闻媒体') 
	 subcat[22]=new Array('2','电视广播','电视广播') 
	 subcat[23]=new Array('2','报纸杂志','报纸杂志') 
	 subcat[25]=new Array('1','幽默笑话','幽默笑话') 
	 subcat[26]=new Array('1','文学小说','文学小说') 
	 subcat[27]=new Array('0','软件下载','软件下载') 
	 subcat[28]=new Array('1','BT资源','BT资源') 
	 subcat[29]=new Array('0','电脑网络','电脑网络') 
	 subcat[30]=new Array('0','硬件资讯','硬件资讯') 
	 subcat[31]=new Array('0','程序编程','程序编程') 
	 subcat[32]=new Array('0','黑客安全','黑客安全') 
	 subcat[33]=new Array('0','网站制作','网站制作') 
	 subcat[34]=new Array('0','搜索引擎','搜索引擎') 
	 subcat[35]=new Array('2','网上购物','网上购物') 
	 subcat[36]=new Array('2','人才招聘','人才招聘') 
	 subcat[37]=new Array('3','留学移民','留学移民') 
	 subcat[38]=new Array('4','教育培训','教育培训') 
	 subcat[39]=new Array('4','考试招生','考试招生') 
	 subcat[40]=new Array('4','论文课件','论文课件') 
	 subcat[41]=new Array('4','英语MBA','英语MBA') 
	 subcat[42]=new Array('4','校园高校','校园高校') 
	 subcat[43]=new Array('4','艺术爱好','艺术爱好') 
	 subcat[44]=new Array('4','少年儿童','少年儿童') 
	 subcat[45]=new Array('4','医疗保健','医疗保健') 
	 subcat[46]=new Array('4','医学医药','医学医药') 
	 subcat[47]=new Array('4','男士女性','男士女性') 
	 subcat[48]=new Array('3','时尚美容','时尚美容') 
	 subcat[49]=new Array('3','消费品牌','消费品牌') 
	 subcat[50]=new Array('3','生活服务','生活服务') 
	 subcat[51]=new Array('3','饮食营养','饮食营养') 
	 subcat[52]=new Array('3','房产家居','房产家居') 
	 subcat[53]=new Array('3','汽车汽配','汽车汽配') 
	 subcat[54]=new Array('3','旅游地图','旅游地图') 
	 subcat[55]=new Array('2','交通物流','交通物流') 
	 subcat[56]=new Array('3','礼品玩具','礼品玩具') 
	 subcat[57]=new Array('3','服装服饰','服装服饰') 
	 subcat[58]=new Array('2','纺织皮革','纺织皮革') 
	 subcat[59]=new Array('3','食品饮料','食品饮料') 
	 subcat[60]=new Array('2','建筑建材','建筑建材') 
	 subcat[61]=new Array('2','投资理财','投资理财') 
	 subcat[62]=new Array('2','财经证券','财经证券') 
	 subcat[63]=new Array('2','商业贸易','商业贸易') 
	 subcat[64]=new Array('2','企业黄页','企业黄页') 
	 subcat[65]=new Array('2','机械五金','机械五金') 
	 subcat[66]=new Array('2','电子电工','电子电工') 
	 subcat[67]=new Array('2','农林牧渔','农林牧渔') 
	 subcat[68]=new Array('2','冶金矿产','冶金矿产') 
	 subcat[69]=new Array('2','化工能源','化工能源') 
	 subcat[70]=new Array('2','广告营销','广告营销') 
	 subcat[71]=new Array('3','法律律师','法律律师') 
	 subcat[75]=new Array('4','社会文化','社会文化') 
	 subcat[77]=new Array('4','科学技术','科学技术') 
	 subcat[79]=new Array('0','免费资源','免费资源') 
  for(j=0;j<biglist.length;j++)   
    if(biglist[j]==locationid){
      locationid=j;
    }
    document.submit_form.smallclass.length=0;//初始化下拉列表，清空下拉数据 
    document.submit_form.smallclass.options[0]=new Option('所有小类','所有小类');//给第一个值 
    for(i=0;i<subcat.length;i++) 
    { 
      if(subcat[i][0]==locationid) 
    {
    document.submit_form.smallclass.options[document.submit_form.smallclass.length]=new Option(subcat[i][1],subcat[i][2]);}//建立option 
  } 
} 